### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by vacSQL** [rm1984/PaReD#1]
thris some ips dont work and show this probleam
like this ip : 216.162.171.100
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PaReD\pared.py", line 237, in <module>
    main(sys.argv[1:])
  File "C:\Users\Administrator\Desktop\PaReD\pared.py", line 221, in main
    print_domains(ip, source, ua, output)
  File "C:\Users\Administrator\Desktop\PaReD\pared.py", line 160, in print_domains
    rv = result[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\dns\resolver.py", line 277, in __getitem__
    raise IndexError
IndexError
--
and can you add threads plz
thank you ^^

**Comment by rm1984** [comment]
Hi,
the bug about the reverse DNS has been fixed.
In your specific case, no reverse DNS and no domains found for the specified IP btw.
Threads will be added in the future as soon as I have some spare time.
Thanks!
